### ISSUE TITLE
How did you get stow to ignore files/dirs in the "stow root"?

### ISSUE THREAD

**Issue by marc1** [idcrook/i-dotfiles#2]
I'm talking about files that start with an underscore (i.e. `__pip`), and your README.md.

Even with sensible settings in my `.stow-global-ignore`, it doesn't seem to want to ignore things in the stow root, or entire packages.

**Comment by idcrook** [comment]
From README "Directories Naming" <https://github.com/idcrook/i-dotfiles#directories-naming>

- leading _ for non packages, eg _pip meaning that these directories must not be stowed

**Comment by idcrook** [comment]
this is not an issue with this repo, but instead a question. 

here's my https://github.com/idcrook/i-dotfiles/blob/main/stow/.stow-global-ignore

perhaps RTM on stow ignore file syntax?

**Comment by idcrook** [comment]
see https://github.com/idcrook/i-dotfiles/blob/main/%40ubuntu/README.md for some example install routines used in Linux environments

**Comment by marc1** [comment]
I was talking about the ability to run `stow *` while ignoring underscore-prefixed packages and files such as READMEs. I have extensively scoured the docs for this, but it does not seem to be a feature.

Just as well, since I guess stow will stow whatever you pass it, i.e. the wildcard glob *.
